{% set version = "1.0" %}
{% set sha256 = "1467d36957e3dafc06060f46059194e8426608866493a0e33b00b6bb7ba55264" %}

package:
  name: DiTaxa
  version: {{ version }}

source:
  url: http://deepbio.info/microbiome/ditaxa/DiTaxa_v{{ version }}.zip
  sha256: {{ sha256 }}

requirements:
  build:
    - python3
    - zlib
  run:
    - python3
    - zlib

test:
  imports:
    - ditaxa

about:
  home: git@github.com:ehsanasgari/DiTaxa.git
  license: Apache License V2
  license_file: LICENSE
  summary:  Nucleotide-pair encoding of 16S rRNA sequences for host phenotype and biomarker detection
